# Generated by Django 5.1.3 on 2024-11-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='servings',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
